#Database connectivity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/last_minute
    username: root
    password: 1998
    driver-class-name: com.mysql.cj.jdbc.Driver

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: lastminuteseats@gmail.com
    password: bsjxqwuabtbswaqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

